{% set name = "transbigdata" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/transbigdata-{{ version }}.tar.gz
  sha256: d036e1cc93b2404716bb672b32fad3b5bcc16d75c2b93d6d85af32588aea3619

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - pandas
    - geopandas
    - shapely
    - scipy
    - matplotlib-base
    - python >={{ python_min }}
    - pykalman
    - osmnx

test:
  imports:
    - transbigdata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ni1o1/transbigdata
  summary: A Python package developed for transportation spatio-temporal big data processing and analysis.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ni1o1
